# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20161009_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.CharField(max_length=64, unique=True, verbose_name='\u6e38\u5ba2ip')),
            ],
        ),
    ]
